; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:d1_mini]
platform = espressif8266
board = d1_mini
framework = arduino
monitor_speed = 115200

; Overclock CPU to 160MHz to minimize active execution time
board_build.f_cpu = 160000000L

; Maximize SPI flash read throughput to reduce instruction cache miss latency
board_build.f_flash = 80000000L
board_build.flash_mode = qio

; Compiler and framework optimizations
build_flags =
    -D NDEBUG
    -D PIO_FRAMEWORK_ARDUINO_LWIP2_LOW_MEMORY